require "rails/generators"
require "rails/generators/named_base"

module SnelDB
  module Generators
    class EventGenerator < Rails::Generators::NamedBase
      source_root File.expand_path("templates", __dir__)

      argument :fields, type: :array, default: [], banner: "field:type field:type"
      class_option :version, type: :numeric, default: nil, desc: "Schema version"

      desc <<-DESC
Description:
    Generates a SnelDB event definition and stores it in config/initializers/sneldb_events.rb

Example:
    rails generate sneldb:event OrderCreated id:uuid amount:float currency:string created_at:datetime

    This will create an event definition for OrderCreated with the specified fields.
      DESC

      def create_event_definition
        @event_name = name.underscore
        @event_class_name = name.camelize
        @fields_hash = parse_fields
        @version = options[:version]

        # Create or append to the events initializer
        events_path = events_initializer_path
        if File.exist?(events_path)
          append_to_file events_path, event_definition_code
        else
          create_file events_path, initializer_template + event_definition_code
        end

        say "Event definition for #{@event_class_name} created!", :green
        say "Run 'rails runner SnelDB::Rails.define_events' to register the event with SnelDB", :yellow
      end

      private

      def parse_fields
        fields.each_with_object({}) do |field_spec, hash|
          field_name, field_type = field_spec.split(":")
          if field_name && field_type
            hash[field_name] = field_type
          else
            raise ArgumentError, "Invalid field format: #{field_spec}. Use format: field_name:type"
          end
        end
      end

      def event_definition_code
        fields_json = @fields_hash.map { |k, v| "      \"#{k}\" => \"#{v}\"" }.join(",\n")
        version_line = @version ? "      version: #{@version},\n" : ""

        <<~RUBY

  # #{@event_class_name} event
  SnelDB::Rails.define_event(
    event_type: "#{@event_name}",
#{version_line}    fields: {
#{fields_json}
    }
  )
        RUBY
      end

      def initializer_template
        <<~RUBY
# SnelDB Event Definitions
# This file is auto-generated by the sneldb:event generator
# Run 'rails runner SnelDB::Rails.define_events' to register events with SnelDB

        RUBY
      end

      def events_initializer_path
        if defined?(Rails)
          Rails.root.join("config", "initializers", "sneldb_events.rb")
        else
          File.join("config", "initializers", "sneldb_events.rb")
        end
      end
    end
  end
end

